net: ti: prueth_core: assign lredev_ops only when CONFIG_HSR is enabled
commit 5bf91c7285dd7ab5a10a945bae125857b7fa4ce1 from
git://git.ti.com/ti-linux-kernel/ti-linux-kernel.git

Currently prueth driver throws below compilation error when CONFIG_HSR is
disabled

drivers/net/ethernet/ti/prueth_core.c:2883:9: error: ‘struct net_device’
has no member named ‘lredev_ops’; did you mean ‘netdev_ops’?
 2883 |   ndev->lredev_ops = &prueth_lredev_ops;
      |         ^~~~~~~~~~
      |         netdev_ops

Fix this by doing assignment only when CONFIG_HSR is enabled

Fixes: commit 093bb5ea4125 ("net: ti: prueth_core: hsr/prp: update for ethtool stats support")
Reported-by: Suman Anna <s-anna@ti.com>
Signed-off-by: Murali Karicheri <m-karicheri2@ti.com>
Signed-off-by: Xulin Sun <xulin.sun@windriver.com>