ARM: OMAP2+: Prevent undefined reference to omap_secure_init
commit 855da027c55da4439274714fd6b35937e915def3 from
git://git.ti.com/ti-linux-kernel/ti-linux-kernel.git

omap_secure_init() will be called from all OMAP2+ platforms during their
init_early() call. This function is in omap-secure.o so include that
in the build for these platforms.

Reported-by: Dan Murphy <dmurphy@ti.com>
Signed-off-by: Andrew F. Davis <afd@ti.com>
Signed-off-by: Xulin Sun <xulin.sun@windriver.com>