soc: ti: k3: k3-navss-desc-pool: fix allmodconfig build
commit a183dd3c97fcbeba1c123340f8afa71cce92a23f from
git://git.ti.com/ti-linux-kernel/ti-linux-kernel.git

include/linux/soc/ti/k3-navss-desc-pool.h:21:61: error: unknown type name ‘dma_addr_t’
void *k3_knav_pool_dma2virt(struct k3_knav_desc_pool *pool, dma_addr_t dma);
                                                                 ^~~~~~~~~~
include/linux/soc/ti/k3-navss-desc-pool.h:24:1: error: unknown type name ‘size_t’
 size_t k3_knav_pool_avail(struct k3_knav_desc_pool *pool);
 ^~~~~~

Fixes: c37937f4c089 ("HACK: soc: ti: k3: add dma descriptors pool")
Signed-off-by: Grygorii Strashko <grygorii.strashko@ti.com>
Signed-off-by: Sekhar Nori <nsekhar@ti.com>
Signed-off-by: Xulin Sun <xulin.sun@windriver.com>